"""Constants utilized in the test cases."""

import os

DATA = "data"
STATE = "state"
MESSAGE = "message"

STATUS_SUCCESS_RESPONSE_CODE = 200
STATUS_NOT_FOUND_RESPONSE_CODE = 404
STATUS_INTERNAL_SERVER_RESPONSE_CODE = 500

VALID_PRODUCT_NAME = "GR_PWA"
NO_SPEC_PRODUCT_NAME = "Test partnumber"
VALID_PRODUCT_REVISION = "1.0"

INVALID_PRODUCT_NAME = "INVALID PRODUCT"

VALID_PRODUCT_GET_SPEC_URL = f"/niscm/public/spec/{VALID_PRODUCT_NAME}/{VALID_PRODUCT_REVISION}"
INVALID_PRODUCT_GET_SPEC_URL = f"/niscm/public/spec/{INVALID_PRODUCT_NAME}/{VALID_PRODUCT_REVISION}"
NO_SPEC_PRODUCT_GET_SPEC_URL = f"/niscm/public/spec/{NO_SPEC_PRODUCT_NAME}/{VALID_PRODUCT_REVISION}"

DISCIPLINE = "Validation"

SUCCESS_STATE_IN_FILE_UPLOAD = 0

VALID_MEASUREMENT_FILE_NAME = "valid_measurement.csv"
VALID_MEASUREMENT_FILE_PATH = os.path.join(os.getcwd(), "tests", "assets", VALID_MEASUREMENT_FILE_NAME)

INVALID_MEASUREMENT_FILE_NAME = "invalid_measurement.csv"
INVALID_MEASUREMENT_FILE_PATH = os.path.join(os.getcwd(), "tests", "assets", INVALID_MEASUREMENT_FILE_NAME)
