"""Constants utilized in the test cases."""

DATA = "data"
STATE = "state"
MESSAGE = "message"

STATUS_SUCCESS = 200
STATUS_NOT_FOUND = 404


VALID_PRODUCT_NAME = "GR_PWA"
NO_SPEC_PRODUCT_NAME = "Test partnumber"
VALID_PRODUCT_REVISION = "1.0"

INVALID_PRODUCT_NAME = "INVALID PRODUCT"

VALID_PRODUCT_GET_SPEC_URL = f"/niscm/public/spec/{VALID_PRODUCT_NAME}/{VALID_PRODUCT_REVISION}"
INVALID_PRODUCT_GET_SPEC_URL = f"/niscm/public/spec/{INVALID_PRODUCT_NAME}/{VALID_PRODUCT_REVISION}"
NO_SPEC_PRODUCT_GET_SPEC_URL = f"/niscm/public/spec/{NO_SPEC_PRODUCT_NAME}/{VALID_PRODUCT_REVISION}"
